/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homedecoration;

import java.awt.FlowLayout;

/**
 *
 * @author aarushisinghal
 */
public class Accessoriesinfo extends javax.swing.JFrame {

    /**
     * Creates new form Accessoriesinfo
     */
    public Accessoriesinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jC1 = new javax.swing.JComboBox();
        jC2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jc3 = new javax.swing.JComboBox();
        jc4 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jc5 = new javax.swing.JComboBox();
        jc6 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jc7 = new javax.swing.JComboBox();
        jc8 = new javax.swing.JComboBox();
        jc9 = new javax.swing.JComboBox();
        jc10 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jP1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt1 = new javax.swing.JLabel();
        jt2 = new javax.swing.JLabel();
        jt3 = new javax.swing.JLabel();
        jt4 = new javax.swing.JLabel();
        jt5 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Phosphate", 3, 14)); // NOI18N
        jLabel1.setText("Pillows");

        jLabel2.setFont(new java.awt.Font("Herculanum", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("We make your choice possible");

        jLabel4.setFont(new java.awt.Font("Phosphate", 3, 14)); // NOI18N
        jLabel4.setText("BedSheets");

        jLabel5.setFont(new java.awt.Font("Phosphate", 3, 14)); // NOI18N
        jLabel5.setText("Comforter");

        jLabel6.setFont(new java.awt.Font("Phosphate", 3, 14)); // NOI18N
        jLabel6.setText("Curtains");

        jC1.setFont(new java.awt.Font("Noteworthy", 3, 13)); // NOI18N
        jC1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\"Select Item\"", "Round  12$", "heart  13$", "oval  14$", "cylinderical  20$", "square  14$" }));
        jC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC1ActionPerformed(evt);
            }
        });

        jC2.setFont(new java.awt.Font("Noteworthy", 3, 13)); // NOI18N
        jC2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\"Select Quantity\"", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC2ActionPerformed(evt);
            }
        });

        jButton1.setText("Price");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jc3.setFont(new java.awt.Font("Noteworthy", 3, 13)); // NOI18N
        jc3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\"Select Size\"", "Double Bed Size 60$", "Single Bed Size 40$" }));
        jc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc3ActionPerformed(evt);
            }
        });

        jc4.setFont(new java.awt.Font("Noteworthy", 3, 13)); // NOI18N
        jc4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\"Select Quantity\"", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jButton2.setText("Price");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jc5.setFont(new java.awt.Font("Noteworthy", 3, 13)); // NOI18N
        jc5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\"Select Size\"", "Large", "Medium", "Small" }));

        jc6.setFont(new java.awt.Font("Noteworthy", 3, 13)); // NOI18N
        jc6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\"Select Quantity\"", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jButton3.setText("Price");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Price");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Price");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Phosphate", 3, 14)); // NOI18N
        jLabel7.setText("Blankets");

        jc7.setFont(new java.awt.Font("Noteworthy", 3, 13)); // NOI18N
        jc7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\"Select Type\"", "shredded", "foldings", "cotton covers", "polyster heavy curtains", "King sized Drape" }));

        jc8.setFont(new java.awt.Font("Noteworthy", 3, 13)); // NOI18N
        jc8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\"Select Quantity\"", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jc9.setFont(new java.awt.Font("Noteworthy", 3, 13)); // NOI18N
        jc9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\"Select Size\"", "Large", "Medium", "Small" }));

        jc10.setFont(new java.awt.Font("Noteworthy", 3, 13)); // NOI18N
        jc10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "\"Select Quantity\"", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jButton6.setFont(new java.awt.Font("Diwan Thuluth", 3, 13)); // NOI18N
        jButton6.setText("TOTAL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homedecoration/images-19.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Kokonor", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("IMAGE PREVIEW OF ITEMS OF EACH SEGMENT");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homedecoration/images-4.jpeg"))); // NOI18N

        javax.swing.GroupLayout jP1Layout = new javax.swing.GroupLayout(jP1);
        jP1.setLayout(jP1Layout);
        jP1Layout.setHorizontalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP1Layout.createSequentialGroup()
                .addGroup(jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel9))
                    .addGroup(jP1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel10)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jP1Layout.setVerticalGroup(
            jP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel9)
                .addGap(147, 147, 147)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(459, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGap(44, 44, 44)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jc5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jc3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jC1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jc7, 0, 1, Short.MAX_VALUE)
                                                .addComponent(jc9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jC2, 0, 166, Short.MAX_VALUE)
                                                .addComponent(jc4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jc8, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jc10, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jt5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jt2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jt4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(15, 15, 15)
                                                    .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jc6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jt3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton3)
                                        .addComponent(jButton4)
                                        .addComponent(jButton5)
                                        .addComponent(jButton2)
                                        .addComponent(jButton1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton4)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton5)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jc10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC1ActionPerformed

    }//GEN-LAST:event_jC1ActionPerformed

    private void jC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jC2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
        if(jC1.getSelectedItem().equals("\"Select Item\""))
          {
             
     jt1.setText("not valid");
       }    
        
        else if(jC1.getSelectedItem().equals("Round  12$"))
          {
             int n= Integer.parseInt(jC2.getSelectedItem().toString());
             int price= n*12;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt1.setText(h.toString());
       }
          else if(jC1.getSelectedItem().equals("heart  13$"))
          {
             int n= Integer.parseInt(jC2.getSelectedItem().toString());
             int price= n*13;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt1.setText(h.toString());
       }
         else if(jC1.getSelectedItem().equals("cylinderical  20$"))
          {
             int n= Integer.parseInt(jC2.getSelectedItem().toString());
             int price= n*20;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt1.setText(h.toString());
       }
         else if(jC1.getSelectedItem().equals("square  14$"))
          {
             int n= Integer.parseInt(jC2.getSelectedItem().toString());
             int price= n*14;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt1.setText(h.toString());
       }
         else if(jC1.getSelectedItem().equals("oval  14$"))
          {
             int n= Integer.parseInt(jC2.getSelectedItem().toString());
             int price= n*14;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt1.setText(h.toString());
       }
        Pillows p= new Pillows();
         jP1.removeAll();
     jP1.setLayout(new FlowLayout());
     jP1.add(p);
     jP1.repaint();
     jP1.validate();
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(jc3.getSelectedItem().equals("\"Select Size\""))
          {
             
     jt2.setText("not valid");
       }
        
      else if(jc3.getSelectedItem().equals("Double Bed Size 60$"))
          {
             int n= Integer.parseInt(jc4.getSelectedItem().toString());
             int price= n*60;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt2.setText(h.toString());
       }
          else if(jc3.getSelectedItem().equals("Single Bed Size 40$"))
          {
             int n= Integer.parseInt(jc4.getSelectedItem().toString());
             int price= n*40;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt2.setText(h.toString());
       }
         
      Bedsheets p= new Bedsheets();
         jP1.removeAll();
     jP1.setLayout(new FlowLayout());
     jP1.add(p);
     jP1.repaint();
     jP1.validate();
                        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(jc5.getSelectedItem().equals("\"Select Size\""))
          {
             
     jt3.setText("not valid");
       }    
        
        else if(jc5.getSelectedItem().equals("Large"))
          {
             int n= Integer.parseInt(jc6.getSelectedItem().toString());
             int price= n*90;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt3.setText(h.toString());
       }
          else if(jc5.getSelectedItem().equals("Medium"))
          {
             int n= Integer.parseInt(jc6.getSelectedItem().toString());
             int price= n*65;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt3.setText(h.toString());
       }
         else if(jc5.getSelectedItem().equals("Small"))
          {
             int n= Integer.parseInt(jc6.getSelectedItem().toString());
             int price= n*45;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt3.setText(h.toString());
       }
        Comforters p= new Comforters();
         jP1.removeAll();
     jP1.setLayout(new FlowLayout());
     jP1.add(p);
     jP1.repaint();
     jP1.validate();
          
                                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
               if(jc7.getSelectedItem().equals("\"Select Type\""))
          {
             
     jt4.setText("not valid");
       }    
        
        else if(jc7.getSelectedItem().equals("shredded"))
          {
             int n= Integer.parseInt(jc8.getSelectedItem().toString());
             int price= n*45;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt4.setText(h.toString());
       }
          else if(jc7.getSelectedItem().equals("foldings"))
          {
             int n= Integer.parseInt(jc8.getSelectedItem().toString());
             int price= n*65;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt4.setText(h.toString());
       }
         else if(jc7.getSelectedItem().equals("polyster heavy curtains"))
          {
             int n= Integer.parseInt(jc8.getSelectedItem().toString());
             int price= n*100;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt4.setText(h.toString());
       }
                else if(jc7.getSelectedItem().equals("King sized Drape"))
          {
             int n= Integer.parseInt(jc8.getSelectedItem().toString());
             int price= n*180;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt4.setText(h.toString());
       }
               else if(jc7.getSelectedItem().equals("cotton covers"))
          {
             int n= Integer.parseInt(jc8.getSelectedItem().toString());
             int price= n*65;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt4.setText(h.toString());
       }
                  curtains p= new curtains();
         jP1.removeAll();
     jP1.setLayout(new FlowLayout());
     jP1.add(p);
     jP1.repaint();
     jP1.validate();
          
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                     if(jc9.getSelectedItem().equals("\"Select Size\""))
          {
             
     jt5.setText("not valid");
       }    
        
        else if(jc9.getSelectedItem().equals("Large"))
          {
             int n= Integer.parseInt(jc10.getSelectedItem().toString());
             int price= n*45;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt5.setText(h.toString());
       }
          else if(jc9.getSelectedItem().equals("Medium"))
          {
             int n= Integer.parseInt(jc10.getSelectedItem().toString());
             int price= n*65;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt5.setText(h.toString());
       }
         else if(jc9.getSelectedItem().equals("Small"))
          {
             int n= Integer.parseInt(jc10.getSelectedItem().toString());
             int price= n*45;
             StringBuilder h= new StringBuilder();
             h.append(price);
     jt5.setText(h.toString());
       }
                     Blanket b= new Blanket();
     jP1.removeAll();
     jP1.setLayout(new FlowLayout());
     jP1.add(b);
     jP1.repaint();
     jP1.validate();
    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        StringBuilder n =new StringBuilder();
        if(jt1.getText().isEmpty())
        {
            jt1.setText("0");
        }
         if(jt2.getText().isEmpty())
        {
            jt2.setText("0");
        }
          if(jt3.getText().isEmpty())
        {
            jt3.setText("0");
        }
          if(jt4.getText().isEmpty())
        {
            jt4.setText("0");
        } if(jt5.getText().isEmpty())
        {
            jt5.setText("0");
        }
   int total = Integer.parseInt(jt1.getText())+Integer.parseInt(jt2.getText())+Integer.parseInt(jt3.getText())+Integer.parseInt(jt4.getText())+Integer.parseInt(jt5.getText());
             String msg= n.append(total).toString();      
              Billing w= new Billing(msg);
              
     jPanel2.removeAll();
     jPanel2.setLayout(new FlowLayout());
     jPanel2.add(w);
     jPanel2.repaint();
     jPanel2.validate();
    
     
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accessoriesinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accessoriesinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accessoriesinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accessoriesinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accessoriesinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jC1;
    private javax.swing.JComboBox jC2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jP1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox jc10;
    private javax.swing.JComboBox jc3;
    private javax.swing.JComboBox jc4;
    private javax.swing.JComboBox jc5;
    private javax.swing.JComboBox jc6;
    private javax.swing.JComboBox jc7;
    private javax.swing.JComboBox jc8;
    private javax.swing.JComboBox jc9;
    private javax.swing.JLabel jt1;
    private javax.swing.JLabel jt2;
    private javax.swing.JLabel jt3;
    private javax.swing.JLabel jt4;
    private javax.swing.JLabel jt5;
    // End of variables declaration//GEN-END:variables
}
