/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homedecoration;


import javax.swing.JFrame;
import javax.swing.JOptionPane;




/**
 *
 * @author aarushisinghal
 */
public class VISA extends javax.swing.JPanel {

    /**
     * Creates new form VISA
     */
    public VISA() {
        initComponents();
       jButton1.setEnabled(false);
    }
 
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jc1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jc2 = new javax.swing.JComboBox();
        jp1 = new javax.swing.JPasswordField();
        jt1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("CARD NUMBER");

        jLabel2.setText("CVV");
        jLabel2.setToolTipText("");

        jLabel3.setText("EXPIRY DATE");

        jc1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MONTH", "JAN", "FEB", "MAR", "APRIL", "MAY", "JUN", "JULY", "AUG", "SEPT", "OCT", "NOV", "DEC" }));

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jc2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YEAR", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp1ActionPerformed(evt);
            }
        });
        jp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jp1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jp1KeyPressed(evt);
            }
        });

        jt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt1ActionPerformed(evt);
            }
        });
        jt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt1KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt1KeyReleased(evt);
            }
        });

        jTextPane1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jTextPane1.setText("3 digits at the backof your card");
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(84, 84, 84))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jc2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt1ActionPerformed
     
    }//GEN-LAST:event_jt1ActionPerformed

    private void jt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt1KeyTyped
              char ch = evt.getKeyChar();

                if (!isNumber(ch)) {
                    evt.consume();
                }
                 if(jt1.getText().equals(""))
        { jButton1.setEnabled(false);
          //  JOptionPane.showMessageDialog(null, "CARD NUMBER FIELD IS EMPTY ", "REQUIRED FIELD", JOptionPane.ERROR_MESSAGE);
        } 
                 else{
                     jButton1.setEnabled(true);
                 }
            
    }

    

    private boolean isNumber(char ch){
        return ch >= '0' && ch <= '9';
    }//GEN-LAST:event_jt1KeyTyped

    private void jt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt1KeyReleased
    
                                
    }//GEN-LAST:event_jt1KeyReleased

    private void jp1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jp1KeyTyped
         char ch = evt.getKeyChar();

                if (!isNumber(ch)) {
                    evt.consume();
                }
        if(jp1.getText().length()>=3 )
        {
            evt.consume();
        }
     
 if(jp1.getText().equals(""))
        {
            //JOptionPane.showMessageDialog(null, "CVV FIELD IS EMPTY ", "REQUIRED FIELD", JOptionPane.ERROR_MESSAGE);
            jButton1.setEnabled(false);
        } 
           else{
                     jButton1.setEnabled(true);
                 } 
 
              
    }//GEN-LAST:event_jp1KeyTyped

    private void jp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp1ActionPerformed
       
 
    }//GEN-LAST:event_jp1ActionPerformed

    private void jp1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jp1KeyPressed
 
        
        
    }//GEN-LAST:event_jp1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(jp1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "CVV FIELD IS EMPTY ", "REQUIRED FIELD", JOptionPane.ERROR_MESSAGE);
           // jButton1.setEnabled(false);
        } 
          if(jt1.getText().equals(""))
        { //jButton1.setEnabled(false);
            JOptionPane.showMessageDialog(null, "CARD NUMBER FIELD IS EMPTY ", "REQUIRED FIELD", JOptionPane.ERROR_MESSAGE);
        } 
        if(jc1.getSelectedItem().equals("MONTH")&& jc2.getSelectedItem().equals("YEAR"))
        {
             JOptionPane.showMessageDialog(null, "MONTH OR YEAR NOT SELECTED ", "REQUIRED FIELD", JOptionPane.ERROR_MESSAGE);
        }
       
          else{
                 JFrame GO =new GO();
                 GO.setVisible(true);
             }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JComboBox jc1;
    private javax.swing.JComboBox jc2;
    private javax.swing.JPasswordField jp1;
    private javax.swing.JTextField jt1;
    // End of variables declaration//GEN-END:variables
}
